server:
  port: 8081

spring:
  # MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${mysql.url}
    username: ${mysql.username}
    password: ${mysql.password}

  # JPA
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  # RedisConfig
  redis:
    host: ${redis.host}
    port: 6379

  # SQL Init data
  sql:
    init:
      mode: always
      encoding: UTF-8

  #swagger option
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#  # Mail
#  mail:
#    host: ${mail.host}
#    port: ${mail.port}
#    username: ${mail.username}
#    password: ${mail.userpassword}
#    properties:
#      mail.stmp.auth : true
#      mail.stmp.ssl.enable: true
#      mail.smtp.ssl.trust: smtp.naver.com
# JWT
jwt:
  header: Authorization
  secret: ${env.jwt.secret}
  token-validity-in-seconds: 10000 #1?


